#######################################################################################
# Book settings
title : R Kompendium
author: Julia Niemann-Lenz
logo: 'ijk_logo.png'

# Information about where the book exists on the web
description: >-
  R Kompendium für die kommunikationswissenschaftliche Lehre und als Nachschlagewerk
  
#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/xvariable/r_kompendium
  branch                      : "gh-pages"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
# for the .Rmd files
sphinx:
  config:
    nb_custom_formats:
        .Rmd:
            - jupytext.reads
            - fmt: Rmd

scholar:
  style: apa
