#######################################################################################
# Book settings
title : R Kompendium
author: Julia Niemann-Lenz
logo: 'ijk_logo.png'

# Information about where the book exists on the web
description: >-
  R Kompendium für die kommunikationswissenschaftliche Lehre und als Nachschlagewerk
  
#######################################################################################
# Execution settings
execute:
  execute_notebooks         : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : false
  favicon                   : _static/img/favicon.png
  use_edit_page_button      : false
  use_repository_button     : false
  extra_navbar              : ""
  google_analytics_id       : "" 

# #######################################################################################
# Interact link settings
notebook_interface          : "notebook"

#######################################################################################
repository:
  url                       : https://github.com/xvariable/r_kompendium
  #book_path                 : 
  branch                    : gh-pages
  
# for Google Colab & binder
launch_buttons:
  notebook_interface        : classic # try jupyterlab
  binderhub_url             : https://notebooks.gesis.org/binder
  colab_url                 : "https://colab.research.google.com"

latex:
  latex_engine              : "xelatex"
  latex_documents:
    targetname              : book.tex
    
# for the .Rmd files
sphinx:
  config:
    nb_custom_formats:
        .Rmd:
            - jupytext.reads
            - fmt: Rmd

scholar:
  style: apa
